variables:
 REGISTRY_HOST: 172.19.71.11:5000
 CI_PROJECT_PATH: user
#TEST_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
 TEST_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
 RELEASE_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:latest
 DOCKER_IMAGE: $CI_PROJECT_NAME:latest

stages:
 - build

#before_script:
#- docker info
#- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build:
 stage: build
 tags:
 - runner02
 script:
 - docker build --pull -t $TEST_IMAGE .
 - docker push $TEST_IMAGE
 only:
 - pushes
 - tags